'use client';

import { useEffect, useRef, useState } from 'react';
import Script from 'next/script';
import { ArrowUpRight, ArrowRight, Plus, Minus, Menu, X, Check, ShieldCheck, FileCheck2, Radio, Fingerprint, Layers3, Network, Play, Pause, Copy, Download } from 'lucide-react';
import { VerdictMark, EnsMark, TokenMark } from './marks';
import { evaluate, type Evidence } from '@/lib/policy';

const initial: Evidence = {daysRemaining:30,fresh:true,revoked:false,available:true,riskConflict:false};
const faqs=[
 ['What is Verdict?', 'Verdict is an ENS-first evidence layer for tokenized assets. An asset name connects issuer information, independent audit evidence, and risk signals to a transparent, deterministic policy result.'],
 ['Why use ENS instead of a database?', 'ENS gives the asset a portable name and a hierarchy of independently controlled records. Applications can resolve the same sources without relying on one application’s database or opaque badge.'],
 ['Does POLICY_PASS mean an asset is safe?', 'No. POLICY_PASS means the available evidence satisfies the configured rules. It is not an investment recommendation, a guarantee, or a substitute for your own due diligence.'],
 ['Who can change an audit?', 'The proposed authority model grants the auditor specific record permissions. The issuer cannot rewrite the auditor’s evidence. The production implementation must prove these permissions through resolver reads and transaction results.'],
 ['What happens when evidence expires?', 'An expired audit, revoked attestation, or stale risk heartbeat blocks the policy. An audit with fewer than 14 days remaining is marked for review. A failed read produces UNAVAILABLE, never an assumed pass.'],
 ['Can agents use the same asset name?', 'Yes, that is the intended design. Agent context and service endpoints are discoverable through the asset’s ENS records, so a person and an agent can inspect the same evidence.'],
 ['Is this connected to a live deployment?', 'This landing page includes a clearly labeled, local interactive example. Live ENSv2 resolution, onchain permissions, and transactions are separate implementation work described in the product specification.'],
];

function CTA({children='Explore the demo',href='#demo',dark=false}:{children?:React.ReactNode;href?:string;dark?:boolean}){return <a className={'cta '+(dark?'cta-dark':'')} href={href}><span>{children}</span><ArrowRight size={17}/></a>}
function Core({className=''}:{className?:string}){return <img className={'core-image '+className} src="/assets/verification-core.webp" width="1024" height="1536" alt="Chrome and glass verification core surrounding an Ethereum diamond"/>}

export default function Landing(){
 const [menu,setMenu]=useState(false); const [active,setActive]=useState(0); const [openFaq,setOpenFaq]=useState<number|null>(null);
 const [evidence,setEvidence]=useState<Evidence>(initial); const [copied,setCopied]=useState(false); const [videoOpen,setVideoOpen]=useState(false);
 const hero=useRef<HTMLElement>(null); const dialog=useRef<HTMLDialogElement>(null); const trigger=useRef<HTMLButtonElement>(null);
 const result=evaluate(evidence);
 useEffect(()=>{
  const reduce=window.matchMedia('(prefers-reduced-motion: reduce)'); let frame=0;
  const update=()=>{frame=0;if(hero.current)hero.current.style.setProperty('--hero-scroll',String(reduce.matches?0:Math.min(window.scrollY/900,1)));};
  const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);}; window.addEventListener('scroll',scroll,{passive:true});update();
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.08});
  document.querySelectorAll('[data-reveal]').forEach(e=>observer.observe(e));
  return()=>{window.removeEventListener('scroll',scroll);cancelAnimationFrame(frame);observer.disconnect()};
 },[]);
 useEffect(()=>{if(!menu)return; const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[menu]);
 useEffect(()=>{if(videoOpen){dialog.current?.showModal()}else{dialog.current?.close()}},[videoOpen]);
 function scenario(kind:string){setEvidence(kind==='expiry'?{...initial,daysRemaining:0}:kind==='review'?{...initial,daysRemaining:7}:kind==='offline'?{...initial,available:false}:initial)}
 async function copy(){try{await navigator.clipboard.writeText('usd-yield-001.acme.verdict.eth');setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setCopied(false)}}
 function download(){const blob=new Blob([JSON.stringify({example:true,asset:'usd-yield-001.acme.verdict.eth',evidence,decision:result},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='verdict-example-evidence.json';a.click();URL.revokeObjectURL(url)}
 const authority=[{title:'Independent by design',sub:'AUTHORITY',text:'Issuer, auditor, and risk monitor answer from their own authority. No single actor gets to rewrite the whole story.',name:'legal.agent.verdict.eth',icon:ShieldCheck},{title:'Permissions with precision',sub:'ACCESS CONTROL',text:'Give each role only the records it needs. The issuer publishes identity. The auditor owns attestations. The risk monitor keeps signals fresh.',name:'SET_TEXT : audit-*',icon:Fingerprint},{title:'Trust has a lifecycle',sub:'FRESHNESS',text:'Evidence can expire. Permissions can be revoked. The decision reflects what is valid now, not what used to be true.',name:'audit-expiry → policy',icon:Radio}];
 return <>
 <Script src="/scrollcraft.js" strategy="afterInteractive" onReady={()=>{
  const sc=(window as unknown as {ScrollCraft:{instances:unknown[];mount:(root:Document)=>void}}).ScrollCraft;
  if(sc && !sc.instances.length){
   document.querySelector('.architecture-art')?.setAttribute('data-sc-parallax','-0.65');
   document.querySelector('.thesis-art .core-image')?.setAttribute('data-sc-parallax','-1');
   sc.mount(document);
  }
 }}/>
 <a href="#main" className="skip-link">Skip to content</a>
 <header className="site-header"><a href="#" className="wordmark" aria-label="Verdict home"><VerdictMark/>Verdict</a><nav aria-label="Main navigation" className={menu?'nav is-open':'nav'}><a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#architecture" onClick={()=>setMenu(false)}>The protocol</a><a href="#process" onClick={()=>setMenu(false)}>How it works</a><a href="#faq" onClick={()=>setMenu(false)}>FAQ</a><a className="nav-primary" href="#demo" onClick={()=>setMenu(false)}>Explore the demo <ArrowUpRight size={16}/></a></nav><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="main">
 <section className="hero" ref={hero} data-sc-act="flow">
  <div className="hero-grid" aria-hidden="true"/><svg className="contours" viewBox="0 0 1400 900" fill="none" aria-hidden="true">{Array.from({length:14},(_,i)=><path key={i} d={`M ${-300+i*75} -60 C ${100+i*80} 230, ${-100+i*65} 510, ${360+i*55} 960`} stroke="currentColor" strokeWidth={i%3===0?5:1}/>)}</svg>
  <div className="hero-art"><Core/><div className="technical-box box-one"/><div className="technical-box box-two"/><span className="hero-callout callout-one">01 / IDENTITY RESOLVED</span><span className="hero-callout callout-two">02 / EVIDENCE ATTACHED</span><span className="crosshair">+</span></div>
  <div className="hero-copy"><h1>Tokenized assets.<br/>With conviction.</h1><div className="hero-actions"><CTA/><a className="secondary-cta" href="#architecture">Discover the protocol</a></div></div>
  <div className="hero-bottom"><a className="ens-lockup" href="https://ens.domains/" target="_blank" rel="noreferrer"><small>BUILT AROUND</small><EnsMark/><span>ENS</span></a><p>One name connects the asset,<br className="desktop-break"/> the evidence, and the decision.<br className="desktop-break"/> Every authority. Every reason.</p><a href="#demo" className="hero-note"><span><i/> THE VERDICT APPROACH <ArrowUpRight size={15}/></span><strong>Trust the evidence.<br/>Understand the verdict.</strong></a></div>
 </section>
 <section className="decision-section ice-section" id="demo" data-sc-act="flow">
  <div className="section-intro" data-reveal><span className="square-dot"/><h2>Clarity.<br/>Not a black box.</h2><p>An asset is more than its ticker. See who stands behind it, what they attest to, and when their evidence expires.</p><a href="#architecture" className="text-link">Evidence you can inspect <ArrowUpRight size={16}/></a></div>
  <div className="evidence-panel" data-reveal><div className="panel-top"><span>ILLUSTRATIVE EXAMPLE</span><span>ENS ASSET PROFILE <ArrowUpRight size={13}/></span></div><div className="asset-name"><span>ACME / TOKENIZED YIELD</span><h3>USD Yield 001</h3><button onClick={copy} aria-label="Copy example ENS name">usd-yield-001.acme.verdict.eth {copied?<Check size={13}/>:<Copy size={13}/>}</button><span className="copy-status" role="status">{copied?'Copied to clipboard':''}</span></div><div className={'decision-result state-'+result.state.toLowerCase()} aria-live="polite"><span className="status-dot"/>{result.state}<ArrowUpRight size={22}/></div><p className="decision-reason" aria-live="polite">{result.reason}</p><div className="source-rows"><div><FileCheck2 size={16}/><span>Independent audit</span><strong>{evidence.daysRemaining>0?`${evidence.daysRemaining} days left`:'Expired'}</strong></div><div><Radio size={16}/><span>Risk heartbeat</span><strong>{evidence.available?'Fresh':'Read failed'}</strong></div><div><ShieldCheck size={16}/><span>Issuer identity</span><strong>Attached</strong></div></div><button className="panel-download" onClick={download}>DOWNLOAD EXAMPLE EVIDENCE <Download size={14}/></button></div>
  <div className="scenario-list" data-reveal><p className="micro">CHANGE THE EVIDENCE. SEE THE DECISION.</p>{[{key:'valid',n:'01',title:'Evidence in agreement',text:'A valid audit and a fresh risk signal.'},{key:'expiry',n:'02',title:'Let the audit expire',text:'Yesterday’s proof is not enough.'},{key:'review',n:'03',title:'Approaching the deadline',text:'A warning before evidence expires.'},{key:'offline',n:'04',title:'Take the resolver offline',text:'Unknown never becomes a pass.'}].map((s,i)=><button key={s.key} aria-pressed={s.key==='valid'?result.state==='POLICY_PASS':s.key==='expiry'?result.state==='BLOCKED':s.key==='review'?result.state==='REVIEW':result.state==='UNAVAILABLE'} onClick={()=>scenario(s.key)}><span className="scenario-number">{s.n}</span><strong>{s.title}</strong><p>{s.text}</p><ArrowUpRight size={16}/><div className={'scenario-lines lines-'+i}/></button>)}</div>
 </section>
 <section className="architecture" id="architecture" data-sc-act="flow"><div className="architecture-copy"><span className="micro"><i/> THE VERIFICATION STACK</span><h2>Separate authority.<br/>Shared conviction.</h2><div className="authority-list">{authority.map((a,i)=><button key={a.title} onClick={()=>setActive(i)} aria-expanded={active===i} className={active===i?'active':''}><span>{a.sub}</span><h3>{a.title}</h3>{active===i&&<p>{a.text}</p>}<ArrowUpRight size={17}/></button>)}</div></div><div className="architecture-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><Core/><div className="authority-tag" key={active}><span>INDEPENDENT AUTHORITY</span><strong>{authority[active].name}</strong><Check size={15}/></div><span className="drawing-label">FIG. V / THE EVIDENCE CORE</span></div></section>
 <section className="film-section" data-sc-act="flow"><div className="film-frame"><div className="film-wire" aria-hidden="true"><Core/><svg viewBox="0 0 500 600"><path d="M250 15 440 120v355L250 585 60 475V120ZM60 120l190 100 190-100M250 220v365M60 475l190-110 190 110M250 15v350"/></svg></div><div className="film-copy"><VerdictMark/><h2>One name. Every reason.<br/><span>Engineered for verification.</span></h2><div className="film-actions"><CTA/><button ref={trigger} className="film-play" onClick={()=>setVideoOpen(true)}><Play size={14}/> Watch the concept</button></div></div><div className="frame-corner tl"/><div className="frame-corner tr"/><div className="frame-corner bl"/><div className="frame-corner br"/></div></section>
 <section className="thesis ice-section" id="about" data-sc-act="flow"><span className="micro"><i/> A NAME FOR WHAT COMES NEXT</span><div className="thesis-text" data-reveal><p>Tokenization brings assets onchain.<br/><span>Verdict brings their evidence with them.</span></p><p className="thesis-body">A shared financial ledger needs a shared way to read trust. ENS connects identity, independent attestations, and agent discovery through one portable asset name.</p><a href="#process" className="text-link">See how it works <ArrowUpRight size={16}/></a></div><div className="thesis-art" aria-hidden="true"><Core/></div></section>
 <section className="process ice-section" id="process" data-sc-act="flow"><div className="process-heading" data-reveal><h2>From an asset.<br/>To an answer.</h2><p>The name is the starting point.<br/>The sources make the difference.</p></div><div className="process-track">{[{icon:Layers3,title:'Name the asset',text:'Give a tokenized asset a canonical ENS identity. Its issuer, ticker, and documents start here.',label:'ASSET → ENS IDENTITY'},{icon:Network,title:'Connect the authorities',text:'Attach separately controlled issuer, auditor, and risk records. Each source keeps its own voice.',label:'IDENTITY → EVIDENCE'},{icon:FileCheck2,title:'Evaluate the evidence',text:'Check validity, expiry, revocation, and freshness against explicit rules. Show the exact reason.',label:'EVIDENCE → POLICY'},{icon:Fingerprint,title:'Resolve it anywhere',text:'Let people and agents discover the same sources through the same name, across client applications.',label:'POLICY → DECISION'}].map((s,i)=><article key={s.title} data-reveal><span className="process-node"><s.icon size={30} strokeWidth={1}/></span><span className="micro">0{i+1} / {s.label}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div><div className="token-strip"><span className="micro">A COMMON LANGUAGE<br/>FOR AN ONCHAIN WORLD</span><div>{['ETH','ENS','USDC','DAI','BTC'].map(t=><span className="token-item" key={t}><TokenMark kind={t}/><span>{t}</span></span>)}</div><p>Illustrative ecosystem marks.<br/>Not endorsements or integrations.</p></div></section>
 <section className="faq ice-section" id="faq" data-sc-act="flow"><div><span className="square-dot"/><h2>FAQ</h2><p>Good questions.<br/>Clear answers.</p></div><div className="faq-list">{faqs.map(([q,a],i)=><div className="faq-item" key={q}><button aria-expanded={openFaq===i} aria-controls={'answer-'+i} onClick={()=>setOpenFaq(openFaq===i?null:i)}><span className="faq-number">{String(i+1).padStart(2,'0')}</span><span>{q}</span>{openFaq===i?<Minus size={15}/>:<Plus size={15}/>}</button><div id={'answer-'+i} hidden={openFaq!==i}><p>{a}</p></div></div>)}</div></section>
 </main>
 <footer className="footer"><div className="footer-top"><div><h2>Conviction starts<br/>with the evidence.</h2><CTA/></div><div className="footer-links"><span className="micro">EXPLORE</span><a href="#about">About Verdict</a><a href="#architecture">The protocol</a><a href="#demo">Interactive example</a></div><div className="footer-links"><span className="micro">LEARN</span><a href="https://ens.domains/" target="_blank" rel="noreferrer">Ethereum Name System <ArrowUpRight size={12}/></a><a href="/verdict-overview.md" download>Project overview <Download size={12}/></a><a href="#faq">FAQ</a></div><a className="back-top" href="#">Back to top <ArrowUpRight size={16}/></a></div><div className="footer-meta"><span><VerdictMark/> verdict.eth</span><p>CONCEPT LANDING PAGE · ENS-FIRST ASSET EVIDENCE</p><small>© {new Date().getFullYear()} Verdict</small></div><div className="footer-word" aria-hidden="true">Verdict</div><p className="footer-disclaimer">Illustrative demo. No live onchain verification. No investment advice.</p></footer>
 <dialog ref={dialog} className="video-dialog" onCancel={()=>setVideoOpen(false)} onClick={e=>{if(e.target===dialog.current)setVideoOpen(false)}} onClose={()=>{setVideoOpen(false);trigger.current?.focus()}}><button className="dialog-close" onClick={()=>setVideoOpen(false)} aria-label="Close concept video"><X/></button><h2>One name. Every reason.</h2>{videoOpen&&<video src="/assets/verdict-concept.mp4" poster="/assets/video-poster.webp" controls autoPlay muted playsInline aria-label="Verdict animated concept film"/>}<p>Original Hyperframes motion concept. Illustrative evidence flow.</p></dialog>
 </>;
}
